name: Build web application
on: [pull_request]
env:
  WORKING_DIRECTORY: './0_Application/Training.Web/'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build 
        #yarn test
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
