name: Cypress testing
on:
  push:
    paths:
      - 0_Application/Training.Web/**
    branches:
      - main
env:
  WORKING_DIRECTORY: './0_Application/Training.Web/'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build 
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Cypress run on chrome
      uses: cypress-io/github-action@v2
      with:
          install: false
          wait-on: 'https://localhost:3000'
          browser: chrome
          project: './0_Application/Training.Web/'
      
    - name: Cypress run on firefox
      uses: cypress-io/github-action@v2
      with:
          # Specify the browser name or path with browser parameter
          browser: firefox
          # Specify the project to run with project parameter
          project: ${{ env.WORKING_DIRECTORY }}
    - name: Cypress run on edge
      uses: cypress-io/github-action@v2
      with:
          # Specify the browser name or path with browser parameter
          browser: edge
